#pragma checksum "C:\Users\marsh\Documents\Visual Studio 2017\Projects\SimpleBlog\SimpleBlog\App.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "E241202340772DCB6D3771668B3E2F85"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBlog
{
    partial class App : global::Windows.UI.Xaml.Application
    {
    }
}

